### ISSUE TITLE
In minimal contour make layers that should not be touched invisible

### ISSUE THREAD

**Issue by marabuuu** [bauerdavid/napari-nD-annotator#43]
Hi @bauerdavid,

When using minimal contour several layers pop up which should not be touched (you also mentioned that in the documentation). Do you think there is a way to make these layers for the user invisible or is this too difficult to implement? I think the minimal contour is a very cool and powerful tool, but it gets very confusing with all these layers open.

Best,
Mara

**Comment by bauerdavid** [comment]
Hey @marabuuu,
unfortunately there's no safe way to hide layer's from the layer list. The current version will hide the layers if you open the plugin before creating any other layers, but for the next version I decided to remove this functionality due to instability. This is because this was implemented by intruding the inner working of the napari UI (which uses Qt), and this created some other bugs, which makes the plugin problematic to work with (see https://github.com/bauerdavid/napari-nD-annotator/issues/38).

For now I am waiting for the napari ecosystem to introduce some functionality which can help with the situation (I've seen that they were working on hidable layers, and also layer grouping, either would be an acceptable solution).

Another thing I can do is to rename these layers to make it more apparent that which layers should be edited, and which shouldn't. If you have any suggestions on this, do tell!

**Comment by bauerdavid** [comment]
Hey @marabuuu,
I will think about this, it would be very good if I could solve this issue. It's not a real solution, but I could remove these layers when the minimal contour tab is not active. But this won't help if you want to use the minimal contour tool...

Wow, thank you very much, I really appreciate it!

David

**Comment by bauerdavid** [comment]
The new version of the plugin was published, which now uses the lock symbols for distinction. As soon as napari has a built-in way to hide layers from the list, I will update the plugin as well.
